apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics
  namespace: default
subjects:
- kind: ServiceAccount
  name: metrics-grabber
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-grabber
  apiGroup: rbac.authorization.k8s.io
